# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Obrary - download free open designs
tagline:             Making it easy to make
description:         'Open Design for {{ site.github.project_title }}'
url:                 http://obrary.com
baseurl:             ''
paginate:            5

# Custom vars
product:			 Template
